name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: step 1 - Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: step 2 - Build project with Maven
      run: mvn -B package --file pom.xml
      
    - name: setp 3 - Compile Code
      run: docker run -it --rm -v ${pwd}:/code --workdir /code maven mvn clean compile -e
